apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: payment-service
  template:
    metadata:
      labels:
        app: payment-service
    spec:
      containers:
      - name: payment-service
        image: your-docker-repo/payment-service:latest  # Replace with your image
        ports:
        - containerPort: 8081
        env:
        - name: PAYMENT_DB_HOST
          value: "payment-db-host"  # Add your database host if required
---
apiVersion: v1
kind: Service
metadata:
  name: payment-service
spec:
  selector:
    app: payment-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8081
  type: ClusterIP  # Change to LoadBalancer if needed

