apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-service-blue
  labels:
    app: product-service
    version: blue
spec:
  replicas: 2
  selector:
    matchLabels:
      app: product-service
      version: blue
  template:
    metadata:
      labels:
        app: product-service
        version: blue
    spec:
      containers:
      - name: product-service
        image: your-docker-repo/product-service:blue-version  # Replace with your blue version image
        ports:
        - containerPort: 8080

