apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: product-service
  template:
    metadata:
      labels:
        app: product-service
    spec:
      containers:
      - name: product-service
        image: your-docker-repo/product-service:latest  # Replace with your image
        ports:
        - containerPort: 8080
        env:
        - name: PRODUCT_DB_HOST
          value: "product-db-host"  # Add your database host if required
---
apiVersion: v1
kind: Service
metadata:
  name: product-service
spec:
  selector:
    app: product-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP  # Change to LoadBalancer if needed

